/**
 * Foundation Template Data
 *
 * This file is AUTO-GENERATED by foundationAdmin.exportTemplate.
 * It is committed to the repository so that new customer databases
 * are seeded with the exact set of records chosen by the developer.
 *
 * DO NOT EDIT MANUALLY — run "تصدير قالب التأسيس" from the superadmin panel.
 *
 * To seed from this file, the bootstrap process calls seedFoundationRecords()
 * from seed-foundation.ts which imports these arrays.
 */

export type FoundationRecord = Record<string, unknown> & {
  foundationKey: string;
  recordPolicy: 'protected' | 'editable' | 'flexible';
};

export interface FoundationData {
  documentJournals:   FoundationRecord[];
  documentTypes:      FoundationRecord[];
  branches:           FoundationRecord[];
  warehouses:         FoundationRecord[];
  units:              FoundationRecord[];
  productGroups:      FoundationRecord[];
  paymentMethods:     FoundationRecord[];
  costCenters:        FoundationRecord[];
  currencies:         FoundationRecord[];
  documentTemplates:  FoundationRecord[];
  postingDefinitions: FoundationRecord[];
  exportedAt: string;
}

export const FOUNDATION_DATA: FoundationData = {
  documentJournals:   [],
  documentTypes:      [],
  branches:           [],
  warehouses:         [],
  units:              [],
  productGroups:      [],
  paymentMethods:     [],
  costCenters:        [],
  currencies:         [],
  documentTemplates:  [],
  postingDefinitions: [],
  exportedAt: '',
};
