uploads = []
generated = []

[[outputs]]
id = "UKuH1M3NkdcSmZ_zcuePP"
uri = "file://OneSoft-ERP-backup-20260511.tar.gz"
type = "unspecified"
title = "OneSoft ERP - نسخة احتياطية 2026-05-11"

[[outputs]]
id = "38OFMUNG0zHEF73i97MA9"
uri = "file://OneSoft-ERP-source.tar.gz"
type = "unspecified"
title = "OneSoft ERP — Source Code"

[[outputs]]
id = "QfwJ93vbkJP9nTreesPsg"
uri = "file://OneSoft-ERP-source_20260511_0341.tar.gz"
type = "unspecified"
title = "OneSoft ERP — 2026-05-11 03:41"

[[outputs]]
id = "SJQ9ip4XQBFy4UaJ5X-jw"
uri = "file://onesoft-erp-backup.zip"
type = "unspecified"
title = "OneSoft ERP — نسخة احتياطية كاملة"

[[outputs]]
id = "FX9LvOR0tqP2iqP7ByxUz"
uri = "file://onesoft-erp-backup-2026-05-12.zip"
type = "unspecified"
title = "OneSoft ERP — نسخة احتياطية 2026-05-12"

[[outputs]]
id = "GmODfKtSA9UEeFC_iFA7R"
uri = "file://OneSoft_ERP_2026-05-13.tar.gz"
type = "unspecified"
title = "OneSoft ERP — نسخة احتياطية 2026-05-13"

[[outputs]]
id = "YbNr2K1SzXt0hBYdkhDOc"
uri = "file://onesoft-erp-source.zip"
type = "unspecified"
title = "OneSoft ERP — كود المصدر (نسخة احتياطية)"
